name: 'DTS Rebuild Action'
description: 'Rebuilds static DTS collection file.'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  collectionFile:
    description: 'The path to save the collection.json file'
    required: true
  basePublicURL:
    description: 'The public url for the collection.json file'
    required: true
  errorFile:
    description: 'The path to save the error file'
    required: true
  frequency:
    description: 'How often the job runs, in milliseconds. 24 hours by default'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'