name: 'DTS Rebuild Action'
description: 'Rebuilds static DTS collection file.'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  collectionFile:
    description: 'The path to save the collection.json file'
    required: true
  permanentBaseInscriptionURI:
    description: 'The public URI for an inscription.'
    required: true
  permanentBaseInscriptionDownloadURL:
    description: 'The public url from which to download an inscription'
    required: true
  errorFile:
    description: 'The path to save the error file'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'